### PR TITLE
Helloween refactor

### PR DESCRIPTION
**Pull request by joffreykern**
Major changes in this pull request :
* Improve code lisibility (remove the single method pattern)
* Improve anchor generation
* Insert Linq.ts library

### CODE REVIEW

**Comment by joffreykern** [comment]
@peter-perot I add your purpose on this pull request :) 

If you wish, you can review it and submit comments on it!

**Comment by peter-perot** [comment]
@joffreykern: Look's good to me.

One question: What has changed concerning anchor generation? Did you improve the algorithm, or did you change the anchor names which are generated?

**Comment by joffreykern** [comment]
@peter-perot The anchor generation was ``mytitlewithoutspecialchar-{index}``, where {index} was the position of the header in my list. 
Now, I add ``-{index}`` only if there is an other header with the same anchor.

**Comment by peter-perot** [comment]
@joffreykern:  Ok, I [see](https://github.com/joffreykern/vscode-markdown-toc/blob/43c592bcd927db443cd7327b989215e9f96a0323/src/extension.ts#L136). LGTM.

**Comment by joffreykern** [comment]
@peter-perot 1.3.0 is not available on marketplace! Feel free to add a review or report any new bugs :) Thanks for your help !

**Comment by peter-perot** [comment]
@joffreykern: Thank you. Review added. :-)

**Pull request merged**
